---
# file roles/notifications/tasks/main.yml

- name: download spotify gpg key
  ansible.builtin.get_url:
    url: https://download.spotify.com/debian/pubkey_0D811D58.gpg
    dest: "/tmp/pubkey_0D811D58.gpg"

- name: import spotify key
  gpg_key:
    file: "/tmp/pubkey_0D811D58.gpg"

- name: install required packages
  aur:
    use: paru
    name:
      - spotify
      - spotifyd
      - cava
      # required for notifications
      #- playerctl
      
- name: create .config/spotifyd directory
  ansible.builtin.file:
    path: ~/.config/spotifyd
    owner: "{{archusername.stdout}}"
    group: "{{archgroup.stdout}}"
    mode: '0755'
    state: directory

- name: setup spotifyd.conf
  ansible.builtin.copy:
    src: files/avault-spotifyd.conf
    dest: ~/.config/spotifyd/spotifyd.conf
    owner: "{{archusername.stdout}}"
    group: "{{archgroup.stdout}}"
    mode: '0644'

# Commenting out until we implement notifications
# - name: setup spotifyd-notifications.sh
#   ansible.builtin.copy:
#     sst: ~/.config/spotifyd/spotifyd-notifications.sh
#     ownerrc: files/spotifyd-notifications.sh
#     de: "{{archusername.stdout}}"
#     group: "{{archgroup.stdout}}"
#     mode: '0755'

- name: setup spotifyd.service
  ansible.builtin.copy:
    src: files/spotifyd.service
    dest: ~/.config/systemd/user/spotifyd.service
    owner: "{{archusername.stdout}}"
    group: "{{archgroup.stdout}}"
    mode: '0644'
  notify:
    - restart spotifyd

- name: start spotifyd.service
  ansible.builtin.systemd:
    name: spotifyd.service
    enabled: yes
    scope: user
    state: started