---
# file roles/openssh/tasks/main.yml

- name: install required packages
  aur:
    use: paru
    name:
      - openssh

- name: create .ssh directory
  ansible.builtin.file:
    path: ~/.ssh
    owner: "{{archusername.stdout}}"
    group: "{{archgroup.stdout}}"
    mode: '0700'
    state: directory

- name: setup id_rsa
  ansible.builtin.copy:
    src: files/avault-id_rsa
    dest: ~/.ssh/id_rsa
    owner: "{{archusername.stdout}}"
    group: "{{archgroup.stdout}}"
    mode: '0600'

- name: setup id_rsa.pub
  ansible.builtin.copy:
    src: files/id_rsa.pub
    dest: ~/.ssh/id_rsa.pub
    owner: "{{archusername.stdout}}"
    group: "{{archgroup.stdout}}"
    mode: '0644'

- name: setup authorized_keys
  ansible.builtin.copy:
    src: files/authorized_keys
    dest: ~/.ssh/authorized_keys
    owner: "{{archusername.stdout}}"
    group: "{{archgroup.stdout}}"
    mode: '0644'

- name: setup .ssh/config
  ansible.builtin.copy:
    src: files/sshconfig
    dest: ~/.ssh/config
    owner: "{{archusername.stdout}}"
    group: "{{archgroup.stdout}}"
    mode: '0600'

- name: setup sshd service
  ansible.builtin.systemd:
    name: sshd
    enabled: yes
    state: started
  become: yes

- name: define ssh-agent service
  ansible.builtin.copy:
    src: files/ssh-agent.service
    dest: ~/.config/systemd/user/ssh-agent.service
    owner: "{{archusername.stdout}}"
    group: "{{archgroup.stdout}}"
    mode: '0644'

- name: setup ssh-agent service
  ansible.builtin.systemd:
    name: ssh-agent
    scope: user
    enabled: yes
    state: started
