---
# file roles/archbase/tasks/main.yml

- name: install required packages
  aur:
    use: paru
    name:
      - bat
      - exa
      - fish
      - fd
      - htop
      - imagemagick
      - linux-headers
      - linux-zen-headers
      - neovim
      - man-db
      - procs
      - ripgrep
      - rsync
      - tldr
      - tree
      - usbutils
      - wget
      - xdg-user-dirs
      - youtube-dl

- name: setup .bashrc
  ansible.builtin.copy:
    src: files/bashrc
    dest: ~/.bashrc
    owner: "{{archusername.stdout}}"
    group: "{{archgroup.stdout}}"
    mode: '0644'
    backup: yes

- name: setup .bash_profile
  ansible.builtin.copy:
    src: files/bash_profile
    dest: ~/.bash_profile
    owner: "{{archusername.stdout}}"
    group: "{{archgroup.stdout}}"
    mode: '0644'
    backup: yes

- name: setup .gitconfig
  ansible.builtin.copy:
    src: files/avault-gitconfig
    dest: ~/.gitconfig
    owner: "{{archusername.stdout}}"
    group: "{{archgroup.stdout}}"
    mode: '0644'

- name: setup /etc/pacman.conf
  ansible.builtin.copy:
    src: files/pacman.conf
    dest: /etc/pacman.conf
    owner: root
    group: root
    mode: '0644'
  become: yes

# required for makemkv access to optical drive
- name: load sg kernel module on boot
  ansible.builtin.copy:
    src: files/sg.conf
    dest: /etc/modules-load.d/sg.conf
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: create .config/systemd directory
  ansible.builtin.file:
    path: ~/.config/systemd
    owner: "{{archusername.stdout}}"
    group: "{{archgroup.stdout}}"
    mode: '0755'
    state: directory

- name: create projects directory
  ansible.builtin.file:
    path: ~/projects
    owner: "{{archusername.stdout}}"
    group: "{{archgroup.stdout}}"
    mode: '0755'
    state: directory

- name: create projects/ansible directory
  ansible.builtin.file:
    path: ~/projects/ansible
    owner: "{{archusername.stdout}}"
    group: "{{archgroup.stdout}}"
    mode: '0755'
    state: directory

- name: create .config/systemd/user directory
  ansible.builtin.file:
    path: ~/.config/systemd/user
    owner: "{{archusername.stdout}}"
    group: "{{archgroup.stdout}}"
    mode: '0755'
    state: directory

# Uncomment if you experience keyserver connectivity problems    
# - name: change default keyserver to keyserver.ubuntu.com
#   ansible.builtin.copy:
#     src: files/gpg.conf
#     dest: /etc/pacman.d/gnupg/gpg.conf
#     owner: root
#     group: root
#     mode: '0644'
#     backup: yes
#   become: yes