---
# file roles/docker/tasks/main.yml

- name: install required packages
  aur:
    use: paru
    name:
      - docker

- name: start docker service
  ansible.builtin.systemd:
    name: docker.service
    enabled: yes
    state: started
  become: yes

- name: add user to docker group
  ansible.builtin.user:
    name: "{{archusername.stdout}}"
    groups: docker
    append: yes
  become: yes


