#
# ~/.bashrc
#

# ** MANAGED BY ANSIBLE. CHANGES WILL BE OVERWRITTEN. **

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

alias ls='exa -la --color=always --group-directories-first'
alias ll='exa -l --color=always --group-directories-first'
alias vim='nvim'
alias sudo='sudo '
alias apv='ansible-playbook --ask-vault-pass'
alias cat='bat --theme Dracula'

# flags
alias df='df -h'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

export TERM=xterm-256color
export EDITOR=nvim
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

# disable middle mouse button
xinput set-button-map 8 1 0 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20