---
# file roles/grub/tasks/main.yml

- name: setup /etc/default/grub
  ansible.builtin.copy:
    src: files/grub
    dest: /etc/default/grub
    owner: root
    group: root
    mode: '0644'
    backup: yes
  become: yes
  register: grubconfig

- name: regenerate grub.cfg
  command: grub-mkconfig -o /boot/grub/grub.cfg
  become: yes
  when: grubconfig.changed
